server:
  port: 8085

spring:
  application:
    name: booking-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0        # 100% of requests are traced; reduce in prod
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans   # Zipkin server URL

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %m%n"

message: "Hello from Booking Service (via Config Server)!"
